name: Build

on:
  push:
    branches: [staging]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build CSS
        run: npm run tailwind

      - name: Build javascript
        run: npm run minify

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: beynar
          author_email: arnaud@derbey.dev
          message: "Prepare production"
          add: "assets/tailwind.min.css assets/tailwind.apply.min.css assets/components.min.js snippets/styles.liquid snippets/scripts.liquid"
